SOURCES += \
	tex/00-fourier.tex \
	tex/01-laplace.tex \
	tex/02-ode.tex \
	tex/03-lti.tex \
	tex/correspondence-tables.tex \
	tex/diffeq-laplace.tex \
	tex/hsrstud.sty \
	tex/hsrzf.cls \
	tex/inttra.sty \
	tex/lti-system.tex \
	tex/transformation-relations.tex
